services:  
  db:
    container_name: postgres_container
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "4321:5432"
  # pgadmin:
    # container_name: pgadmin4_container
    # image: dpage/pgadmin4:5.6
    # restart: always
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #   PGADMIN_DEFAULT_PASSWORD: root
    # ports:
    #   - "5050:80"
